version: "3.9"

services:

  app:
    image: employee-api:latest
    container_name: employee-api

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    restart: unless-stopped
